// Code generated by MockGen. DO NOT EDIT.
// Source: model.go
//
// Generated by this command:
//
//	mockgen -source=model.go -destination=model_mock.go -package=ratelimiter
//

// Package ratelimiter is a generated GoMock package.
package ratelimiter

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	rate "golang.org/x/time/rate"
)

// MockIPRateLimiter is a mock of IPRateLimiter interface.
type MockIPRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockIPRateLimiterMockRecorder
	isgomock struct{}
}

// MockIPRateLimiterMockRecorder is the mock recorder for MockIPRateLimiter.
type MockIPRateLimiterMockRecorder struct {
	mock *MockIPRateLimiter
}

// NewMockIPRateLimiter creates a new mock instance.
func NewMockIPRateLimiter(ctrl *gomock.Controller) *MockIPRateLimiter {
	mock := &MockIPRateLimiter{ctrl: ctrl}
	mock.recorder = &MockIPRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPRateLimiter) EXPECT() *MockIPRateLimiterMockRecorder {
	return m.recorder
}

// GetLimiter mocks base method.
func (m *MockIPRateLimiter) GetLimiter(ip string) *rate.Limiter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimiter", ip)
	ret0, _ := ret[0].(*rate.Limiter)
	return ret0
}

// GetLimiter indicates an expected call of GetLimiter.
func (mr *MockIPRateLimiterMockRecorder) GetLimiter(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimiter", reflect.TypeOf((*MockIPRateLimiter)(nil).GetLimiter), ip)
}

// StartCleanUp mocks base method.
func (m *MockIPRateLimiter) StartCleanUp(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartCleanUp", ctx)
}

// StartCleanUp indicates an expected call of StartCleanUp.
func (mr *MockIPRateLimiterMockRecorder) StartCleanUp(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCleanUp", reflect.TypeOf((*MockIPRateLimiter)(nil).StartCleanUp), ctx)
}
